export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";

export const SAVE_SHIPPING_ADDRESS_REQUEST = "SAVE_SHIPPING_ADDRESS_REQUEST";
export const SAVE_SHIPPING_ADDRESS_SUCCESS = "SAVE_SHIPPING_ADDRESS_SUCCESS";
export const SAVE_SHIPPING_ADDRESS_FAIL = "SAVE_SHIPPING_ADDRESS_FAIL";

export const VERIFY_SHIPPING_ADDRESS_REQUEST =
  "VERIFY_SHIPPING_ADDRESS_REQUEST";
export const VERIFY_SHIPPING_ADDRESS_SUCCESS =
  "VERIFY_SHIPPING_ADDRESS_SUCCESS";
export const VERIFY_SHIPPING_ADDRESS_FAIL = "VERIFY_SHIPPING_ADDRESS_FAIL";
