export const PRODUCT_SLIDER_REQUEST = "PRODUCT_SLIDER_REQUEST";
export const PRODUCT_SLIDER_SUCCESS = "PRODUCT_SLIDER_SUCCESS";
export const PRODUCT_SLIDER_FAIL = "PRODUCT_SLIDER_FAIL";

export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_LIST_BY_CATEGORY_REQUEST =
  "PRODUCT_LIST_BY_CATEGORY_REQUEST";
export const PRODUCT_LIST_BY_CATEGORY_SUCCESS =
  "PRODUCT_LIST_BY_CATEGORY_SUCCESS";
export const PRODUCT_LIST_BY_CATEGORY_FAIL = "PRODUCT_LIST_BY_CATEGORY_FAIL";

export const PRODUCT_LIST_BY_COMBO_REQUEST =
  "PRODUCT_LIST_BY_COMBO_REQUEST";
export const PRODUCT_LIST_BY_COMBO_SUCCESS =
  "PRODUCT_LIST_BY_COMBO_SUCCESS";
export const PRODUCT_LIST_BY_COMBO_FAIL = "PRODUCT_LIST_BY_COMBO_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";


export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";
